### ISSUE TITLE
Adding more entities, perhaps?

### ISSUE THREAD

**Issue by hikmatsp** [babobski/HTML-Entities#1]
I just found the package for my Komodo 9... its a bit late.. lol and  found your package is very useful. Thank you. If I want to add more entities to the package. What can I do since I'm kind of new to Github. I am using a Win7 machine and a new Ubuntu user.
Btw, the entities I want add is from this page http://www.kelasabil.com/satelit/list-html-char

**Comment by babobski** [comment]
@hikmatsp I know the addon do not contains all the entities that are available.
There are a lot more entities ( [html5 special chars](https://dev.w3.org/html5/html-author/charref) )
I don't want to include all the entities, because I think there are enties you would almost never use.
Adding all the entities would impact the usability of the side pane, as you will have to search trough more characters.

If you have characters you are missing, you can send me a list( `&sung;`, `&#9834`, and  &sung;) with the entities you want to add.
Or you can fork the repo and create a pull request with the new entities
